### ISSUE TITLE
Incorrect numpy version in nb-requirements.txt causes example to fail

### ISSUE THREAD

**Issue by utherp0** [rh-aiservices-bu/metrobus-repairs-nlp-workshop#22]
This repo is used in a RHD Learning Path, which tells the user to follow the instructions in 01-create-claims-classification.ipynb

The !pip install -r nb-requirements.txt command fails at the numpy import

By manually changing the nb-requirements.txt file to:

markovify==0.9.3
tensorflow==2.7.0
scikit-learn==0.24.1
numpy==1.26.0
pandas==1.2.4
keras==2.7.0

The installation and example works. Note the new numpy version

**Comment by guimou** [comment]
Fixed by #20
